I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 567, in script
    uaer "왜?"
Exception: Sayer 'uaer' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 567, in script
    uaer "왜?"
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\asus\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'uaer' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Our Blue Horizon 1.0
Thu Oct 26 02:54:22 2023
